name: Deploy PDF Workflow Agents

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy_chess_agent:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - name: Restart App
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TELEX_SERVER_SSH_HOST }}
          username: ${{ secrets.TELEX_SERVER_SSH_USER }}
          key: ${{ secrets.TELEX_SERVER_SSH_KEY }}
          script: |
            cd /var/www/pdf_workflow_agents
            git pull origin main
            uv sync
            supervisorctl restart pdf_workflow_agents